# Generated by Django 4.1.2 on 2022-11-16 15:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0017_auto_20221113_0938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Score',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='assignedDoctorId',
            new_name='assignedId',
        ),
    ]
